# file name: docker-compose.yml
# this setup may not work correctly in other major versions!!!
version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass

  wordpress:
    image: wordpress:5-fpm-alpine
    depends_on:
      - db

    container_name: wordpress
    restart: unless-stopped
  
    volumes: 
      - /home/ec2-user/wordpress:/var/www/html
    
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=wordpress

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - /home/ec2-user/wordpress:/var/www/html
      - /home/ec2-user/nginx-conf:/etc/nginx/conf.d
      - /home/ec2-user/certbotdata:/etc/letsencrypt
    ports: 
    - "80:80"
    - "443:443"

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ec2-user/certbotdata:/etc/letsencrypt
      - /home/ec2-user/wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email lbzuluagag@eafit.edu.co --agree-tos --no-eff-email --force-renewal -d lambda-mono.cf
